### ISSUE TITLE
STORAGE_CD environmental variable not working

### ISSUE THREAD

**Issue by ciworks** [rix1337/docker-ripper#114]
Have you read and understood this [part of the readme](https://github.com/rix1337/docker-ripper#do-you-offer-support)?

[X ] YES

[] NO

Setting the `STORAGE_CD` environment field in docker-compose appears to append the directory name specified to the default value `/out/Ripper/CD` rather than creating a new absolute path.

```
version: "3.7"
services:
  ripper:
    image: rix1337/docker-ripper:latest
    privileged: true
    container_name: ripper
    ports:
      - 9090:9090
    environment:
      - BAD_THRESHOLD=3
      - STORAGE_CD=/flac
      - DEBUGTOWEB=false
      - TZ=Europe/London
      - DRIVE=/dev/sr0
    volumes:
      - ./config:/config:rw
      - /srv/media/MUSIC:/FLAC:rw
    devices:
      - /dev/sr0:/dev/sr0
    restart: always
```

Ripped media is then stored in `/out/Ripper/CD/flac` rather than `/flac`
